version: '3.8'

services:
  server:
    image: turzum/ethernetip-server:latest
    container_name: ethernetip-server
    ports:
      - "44818:44818"
      - "502:502"  
    restart: unless-stopped
  client:
    image: turzum/ethernetip-client:latest
    container_name: ethernetip-client
    restart: unless-stopped
